[tool.poetry]
name = "aioqzone"
version = "0.3.1.dev1"
description = "Python wrapper for Qzone web login and Qzone http api."
authors = ["JamzumSum <zzzzss990315@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
homepage = "https://github.com/JamzumSum/aioqzone"
repository = "https://github.com/JamzumSum/aioqzone"
# documentation = "https://github.com/JamzumSum/aioqzone/wiki"

packages = [
    { include = "aioqzone", from = "src" },
    { include = "jssupport", from = "src" },
    { include = "qqqr", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.1"
pydantic = "^1.9.0"
pytz = "^2021.3"
lxml = "^4.8.0"
cssselect = "^1.1.0"
opencv-python-headless = { version = "^4.5.5", markers = "sys_platform == 'linux'" }
opencv-python = { version = "^4.5.5", markers = "sys_platform != 'linux'" }
Sphinx = {version = "^4.4.0", optional = true}
autodoc-pydantic = {version = "^1.6.1", optional = true}
sphinx-autodoc-typehints = {version = "^1.17.0", optional = true}
sphinx-rtd-theme = {version = "^1.0.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-asyncio = "^0.18.2"
pre-commit = "^2.17.0"
black = "^22.1.0"
isort = "^5.10.1"

[tool.poetry.extras]
doc = [
    "Sphinx",
    "autodoc-pydantic",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


# customize begin
[tool.pytest.ini_options]
pythonpath = 'src'
markers = [
    "needuser: Need user interaction, DO NOT use in ci",
    "incremental: xfail succ cases if pred case failed or skipped",
    "upstream: Test cannot run normally due to upstream problems",
]
asyncio_mode = 'strict'
log_cli = 1
log_cli_level = 'WARNING'


[tool.isort]
profile = "google"

[tool.black]
line-length = 99
target-version = ['py310']
