# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Dev CI

on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/ci.yml"
      - ".github/workflows/test.yml"
      - "poetry.lock"
    branches:
      - dev
      - dev/**

jobs:
  test:
    uses: ./.github/workflows/test.yml
    if: "!contains(github.event.head_commit.message, '@no-test')"
    with:
      PYTEST_ARGS: -m "not needuser and not upstream" test
    secrets:
      TEST_UIN: ${{ secrets.TEST_UIN }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

  merge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get beta SHA
        id: get_sha
        run: echo "::set-output name=beta_sha::$(git rev-parse --short beta)"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
          args: -t ${{ needs.test.outputs.package-version }} {{ steps.get_sha.outputs.beta_sha }}..HEAD

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        if: "!contains(github.event.head_commit.message, '@no-pr')"
        with:
          destination_branch: beta
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ needs.test.outputs.package-version }}
          pr_body: ${{ steps.git-cliff.outputs.changelog }}
