name: Sphinx Build and Deploy

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - doc/**
      - ".github/workflows/sphinx.yml"

jobs:
  sphinx-build-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '@no-doc')"
    steps:
      #----------------------------------------------
      #   check-out repo and set-up node & python
      #----------------------------------------------
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry Action
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install --no-interaction -E doc
      #----------------------------------------------
      #             Run sphinx-build
      #----------------------------------------------
      - name: Build HTML
        run: poetry run sphinx-build doc/source doc/build/html -D release=$(poetry version -s)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true
