name: Sphinx Build and Deploy

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - doc/**
      - ".github/workflows/sphinx.yml"

jobs:
  sphinx-build-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '@no-doc')"
    steps:
      #----------------------------------------------
      #     check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install --with docs
      #----------------------------------------------
      #             Run sphinx-build
      #----------------------------------------------
      - name: Build HTML
        run: poetry run sphinx-build doc/source doc/build/html -D release=$(poetry version -s)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true
