name: Sphinx Build and Deploy

on:
  pull_request:
    types:
      - ready_for_review
    branches:
      - beta
  pull_request_target:
    types:
      - closed
    branches:
      - beta

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install Library and Build HTML
        run: |
          poetry install --with docs
          poetry run sphinx-build doc/source doc/build/html -D release=$(poetry version -s)

      - name: Upload artifact
        if: github.event_name == 'pull_request_target'
        uses: actions/upload-pages-artifact@v1
        with:
          path: doc/build/html

  deploy:
    if: github.event_name == 'pull_request_target'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: sphinx-build
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
